stages:
  word-to-pdf:
    cmd: calkit office word-to-pdf paper.docx paper.pdf
    deps:
      - paper.docx
    outs:
      - paper.pdf
  excel-thing:
    cmd: cp data.xlsx data-copy.xlsx
    deps:
      - data.xlsx
    outs:
      - data-copy.xlsx
  stage-3:
    cmd: echo supppppp > lol66.txt
    outs:
      - lol66.txt
