stages:
  word-to-pdf:
    cmd: calkit office word-to-pdf paper.docx paper.pdf
    deps:
      - paper.docx
    outs:
      - paper.pdf
  excel-thing:
    cmd: cp data.xlsx data-copy.xlsx
    deps:
      - data.xlsx
    outs:
      - data-copy.xlsx
  word-2:
    cmd: calkit office word-to-pdf doc.docx --output doc.pdf
    deps:
      - doc.docx
    outs:
      - doc.pdf
